### ISSUE TITLE
Cannot use Symfony\Component\Console\Command\Command as Command because the name is already in use

### ISSUE THREAD

**Issue by Amrit01** [laravel-doctrine/orm#35] opened 2015-09-15 06:23 UTC
When trying to publich vendor

```php artisan vendor:publish --tag="config"```

```PHP Fatal error:  Cannot use Symfony\Component\Console\Command\Command as Command because the name is already in use in /var/www/html/laravel-doctrine/vendor/laravel-doctrine/orm/src/Console/ConvertConfigCommand.php on line 17```

                                                                                                      
  [Symfony\Component\Debug\Exception\FatalErrorException]                                             
  Cannot use Symfony\Component\Console\Command\Command as Command because the name is already in use

**Comment by Amrit01** [comment] 2015-09-15 06:29
making alias as SymfonyCommand Fixed it should i make a PR

**Comment by patrickbrouwers** [comment] 2015-09-15 09:39
I couldn't reproduce the issue strangely, but it should indeed fail. Pushed a fix.

**Closed by patrickbrouwers** 2015-09-15 09:39 UTC

**Comment by FoxxMD** [comment] 2015-09-15 13:18
:+1:
