### ISSUE TITLE
[BUG] Unit tests not working when using :memory: driver sqlite database.

### ISSUE THREAD

**Issue by bigperson** [laravel-doctrine/orm#275] opened 2017-09-13 12:21 UTC
### Package version, Laravel version
Laravel 5.5
Laravel doctrine 1.4
PHPUnit 6.0

### Expected behaviour
Tests must pass success.

### Actual behaviour
Entity manager can not access the tables in databases
Errors:
```
 Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1 no such table: cities
```
### Steps to reproduce the behaviour
/config/database.php
```php
...
'connections' => [
...
        'tests' => [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ],
...
```
/config/doctrine.php
```
...
'connection'    => env('DB_CONNECTION', 'mysql'),
...
```
phpunit.xml
```
<env name="DB_CONNECTION" value="tests"/>
```
ExampleTest.php
```
/** @var \Doctrine\ORM\EntityManagerInterface */
    protected $em;

    /**
     * @return void
     */
    public function setUp()
    {
        parent::setUp();
        $this->em = $this->app->make(EntityManagerInterface::class);
    }

    /**
     * {@inheritDoc}
     */
    protected function tearDown()
    {
        parent::tearDown();

        $this->em->close();
        $this->em = null;
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        \DB::table('cities')->insert(['name'=>'test']); //Working
        entity(City::class)->create(); //crashed
        $city = (new City())->setName('test');
        $this->em->persist($city);
        $this->em->flush(); //crashed
        $cities = $this->em->getRepository(City::class)->findAll(); //crashed

        $this->assertCount(3, $cities);
    }
```

**Comment by elambro** [comment] 2017-11-15 08:22
Do you have a 'create_cities_table' migration?

**Comment by bicatu** [comment] 2017-11-25 01:21
I have similar issue (not same table of course), but I do have the VersionXXX files that when I run from the console create the tables I am looking for. (when I call the same methods myself not from phpunit they work)

**Comment by garret-gunter** [comment] 2018-02-13 16:56
I don't see where you are running the migrations.  We use in memory sqlite for our tests.  We haven't had this issue.  Have you tried adding the helper trait for refreshing the database during tests?  It should be in the laravel doctrine migrations package.

**Comment by patrickbrouwers** [comment] 2018-02-27 12:48
Cannot reproduce

**Comment by dallincoons** [comment] 2018-03-16 19:00
I have the same issue, I had to use a sqlite file instead of the in-memory version. I'm using Orchestra Testbench.

**Comment by nospoon** [comment] 2018-05-09 09:41
I think this might be related to running the tests inside vm.

**Comment by R3VoLuT1OneR** [comment] 2018-05-15 23:36
I have same problem.
Doctrine connection and Laravel `DatabaseManager` connections have different `PDOConnection`.
So `Illuminate\Foundation\Testing\RefreshDatabase` trait not working.
So tests not working with default Laravel migrations.

**Comment by patrickbrouwers** [comment] 2018-05-28 08:55
You cannot use that trait as indeed we don't share the PDOConnection

**Comment by xxRockOnxx** [comment] 2018-06-16 15:26
Any workaround available yet? I'm having this problem also. Can confirm this is a bug.

More info:
```
setUp()
{
    parent::setUp();
    Artisan::call('migrate'); // Works properly
    \DB::statement('SELECT * FROM tablename'); // works fine

     // Scenario 2
     parent::setUp();
     \DB::statement('SELECT * FROM tablename'); // Exception
}
```

This just confirms it again. Not sure whether it is `laravel-doctrine's` problem or `doctrine` itself.

**Comment by Stolz** [comment] 2018-09-07 01:46
This is my workaround so far. Provided you set up `phpunit.xml` and `config/database.php` as @bigperson  mentioned, in order to have the `RefreshDatabase` behavior working with Docrine make your tests to use this trait  instead of `Illuminate\Foundation\Testing\RefreshDatabase`

```php
<?php

namespace Tests\Traits;

use Illuminate\Contracts\Console\Kernel;

trait RefreshDatabase
{
    use \Illuminate\Foundation\Testing\RefreshDatabase;

    /**
     * Begin a database transaction on the testing database.
     *
     * @return void
     */
    public function beginDatabaseTransaction()
    {
        $connection = $this->app->make('em')->getConnection();
        $connection->beginTransaction();
        
        $this->beforeApplicationDestroyed(function () use ($connection) {
            $connection->rollBack();
        });
    }

    /**
     * Refresh the in-memory database.
     *
     * @return void
     */
    protected function refreshInMemoryDatabase()
    {
        $this->artisan('doctrine:schema:create');

        $this->app[Kernel::class]->setArtisan(null);
    }
}
```
It works without problems is several of my projects although for others I get `Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getCreateSequenceSQL' is not supported by platform` error but at least DB schema seems to be successfully created in memory and my tests run faster now.

If anyone has a better approach please let me know.

**Comment by bicatu** [comment] 2018-10-02 00:52
Hi, any updates on this one?

**Comment by hamraniali** [comment] 2020-03-17 10:51
sdada

**Comment by TomHAnderson** [comment] 2024-10-22 23:27
Closing; expired.

**Closed as completed by TomHAnderson** 2024-10-22 23:27 UTC
